name: Massive Scraper Matrix

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-visits:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      # This is the concurrency limit for free accounts
      max-parallel: 20
      
      # ------------------------------------------------------------------
      # --- THE FIX IS HERE ---
      # We define the matrix with a direct list instead of the invalid range() function.
      # This creates 20 parallel jobs, utilizing the maximum concurrency.
      # ------------------------------------------------------------------
      matrix:
        runner: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4 libcups2 libatk1.0-0 libatk-bridge2.0-0 libatspi2.0-0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxkbcommon0
      
      - name: Install Python Libraries and Browser
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Run Python Visit Script
        env:
          TARGET_URL: "https://colle-pedia.blogspot.com/"
          RUNNER_ID: ${{ matrix.runner }}
        run: python app.py
