name: Massive Tor Visits with NEWNYM

on:
  schedule:
    - cron: '*/5 * * * *'  # كل 5 دقائق
  workflow_dispatch:

jobs:
  run-visits:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        runner: [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4 libcups2 libatk1.0-0 \
          libatk-bridge2.0-0 libatspi2.0-0 libxcomposite1 libxdamage1 \
          libxrandr2 libgbm1 libxkbcommon0 tor netcat-openbsd

      - name: Configure Tor for Japan
        run: |
          echo "SocksPort 9050" | sudo tee /etc/tor/torrc
          echo "ControlPort 9051" | sudo tee -a /etc/tor/torrc
          echo "ExitNodes {JP}" | sudo tee -a /etc/tor/torrc
          echo "StrictNodes 1" | sudo tee -a /etc/tor/torrc
          echo "CookieAuthentication 0" | sudo tee -a /etc/tor/torrc
          sudo service tor restart
          sleep 15  # وقت لي Tor bootstrapping

      - name: Install Python libraries & Playwright
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Run visit script
        env:
          TARGET_URL: "https://colle-pedia.blogspot.com/"
          RUNNER_ID: ${{ matrix.runner }}
          PROXY_URL: "socks5://127.0.0.1:9050"
        run: python app.py
