name: Massive Scraper Matrix with Tor (Japan Exit)

on:
  schedule:
    # Runs every 5 minutes
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  run-visits:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      max-parallel: 20
      matrix:
        runner: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3 libnspr4 libcups2 libatk1.0-0 libatk-bridge2.0-0 libatspi2.0-0 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxkbcommon0
      
      # --- الجديد: تعديل إعدادات Tor لاختيار اليابان ---
      - name: Install, Configure, and Start Tor Service for Japan
        run: |
          sudo apt-get install -y tor
          # --- Tell Tor to only use exit nodes in Japan ---
          echo "ExitNodes {JP}" | sudo tee -a /etc/tor/torrc
          echo "StrictNodes 1" | sudo tee -a /etc/tor/torrc
          
          # --- Restart Tor to apply the new settings ---
          sudo service tor restart
          
          echo "Waiting for Tor to bootstrap with a Japanese node..."
          # We wait a bit longer because finding a specific country circuit can be slower
          sleep 20 
          echo "Tor service should be running with a Japanese exit node."

      - name: Install Python Libraries and Browser
        run: |
          python -m pip install --upgrade pip
          pip install playwright
          playwright install chromium

      - name: Run Python Visit Script
        env:
          TARGET_URL: "https://colle-pedia.blogspot.com/"
          RUNNER_ID: ${{ matrix.runner }}
          PROXY_URL: "socks5://127.0.0.1:9050"
        run: python app.py
